using System.Text;

namespace Forge.Operations.Generators;

/// <summary>
/// Emits a partial class fragment that adds active-record CRUD methods to every
/// <c>[Entity]</c>-annotated type.
/// </summary>
internal static class EntityOperationsEmitter
{
    private const string Ops = "global::Forge.Operations.EntityOperations";

    public static string Emit(string namespaceName, string typeName, bool isSealed, bool isSubtype = false)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNs = namespaceName.Length > 0;
        if (hasNs) sb.Append("namespace ").Append(namespaceName).AppendLine(";").AppendLine();

        sb.Append(isSealed ? "sealed " : "")
          .Append("partial class ")
          .AppendLine(typeName)
          .AppendLine("{");

        // Entity subtypes inherit instance methods from their parent entity, so we must
        // emit `new` to suppress the CS0108 hide-by-name warning.
        var newMod = isSubtype ? "new " : "";

        // ── Instance: Create ─────────────────────────────────────────────────
        sb.Append("    /// <summary>Persist this entity as a new record (<c>WriteMode.Create</c>).</summary>").AppendLine();
        sb.Append("    public ").Append(newMod).Append("global::System.Threading.Tasks.ValueTask CreateAsync(")
          .AppendLine("global::System.Threading.CancellationToken cancellationToken = default)");
        sb.Append("        => ").Append(Ops).Append(".CreateAsync(this, cancellationToken);").AppendLine();
        sb.AppendLine();

        // ── Instance: Update ─────────────────────────────────────────────────
        sb.AppendLine("    /// <summary>Replace this entity in the store (<c>WriteMode.Replace</c>).</summary>");
        sb.Append("    public ").Append(newMod).Append("global::System.Threading.Tasks.ValueTask UpdateAsync(")
          .AppendLine("global::System.Threading.CancellationToken cancellationToken = default)");
        sb.Append("        => ").Append(Ops).Append(".UpdateAsync(this, cancellationToken);").AppendLine();
        sb.AppendLine();

        // ── Instance: Delete ─────────────────────────────────────────────────
        sb.AppendLine("    /// <summary>Delete this entity from the store by IRI.</summary>");
        sb.Append("    public ").Append(newMod).Append("global::System.Threading.Tasks.ValueTask DeleteAsync(")
          .AppendLine("global::System.Threading.CancellationToken cancellationToken = default)");
        sb.Append("        => ").Append(Ops).Append(".DeleteAsync(Iri, cancellationToken);").AppendLine();
        sb.AppendLine();

        // ── Static: Read ─────────────────────────────────────────────────────
        sb.AppendLine("    /// <summary>Load a single entity by IRI, or <see langword=\"null\"/> if absent.</summary>");
        sb.Append("    public static ").Append(newMod).Append("global::System.Threading.Tasks.ValueTask<").Append(typeName)
          .Append("?> ReadAsync(string iri, ")
          .AppendLine("global::System.Threading.CancellationToken cancellationToken = default)");
        sb.Append("        => ").Append(Ops).Append(".ReadAsync<").Append(typeName)
          .Append(">(iri, cancellationToken);").AppendLine();
        sb.AppendLine();

        // ── Static: List ─────────────────────────────────────────────────────
        sb.AppendLine("    /// <summary>Stream all entities of this type from the store.</summary>");
        sb.Append("    public static ").Append(newMod).Append("global::System.Collections.Generic.IAsyncEnumerable<").Append(typeName)
          .Append("> ListAsync(")
          .AppendLine("global::System.Threading.CancellationToken cancellationToken = default)");
        sb.Append("        => ").Append(Ops).Append(".ListAsync<").Append(typeName)
          .Append(">(cancellationToken);").AppendLine();
        sb.AppendLine();

        sb.AppendLine("}");
        return sb.ToString();
    }
}
