using System.Runtime.CompilerServices;

namespace Forge.Entity;

/// <summary>
/// A lazy reference to another entity: knows the IRI immediately, may not yet hold the value.
/// Tri-state: Unloaded / Loaded(value) / Loaded(null when absent in store).
/// </summary>
/// <remarks>
/// This struct is awaitable so the user-facing partial property <c>public Bar? Bar { get; }</c>
/// generated by the source generator can be written as <c>await foo.Bar</c>.
/// Generated code wraps an internal <see cref="EntityRef{T}"/> field.
/// </remarks>
public sealed class EntityRef<T> where T : class, IEntity
{
    private enum State : byte { Unloaded, Loaded, LoadedNull }

    private readonly string _iri;
    private State _state;
    private T? _value;

    private EntityRef(string iri, State state, T? value)
    {
        _iri = iri;
        _state = state;
        _value = value;
    }

    /// <summary>The IRI of the referenced entity. Always known.</summary>
    public string Iri => _iri ?? throw new InvalidOperationException("EntityRef has no IRI assigned.");

    public bool IsLoaded => _state != State.Unloaded;
    public bool IsNull => _state == State.LoadedNull;
    public bool HasValue => _state == State.Loaded;

    /// <summary>
    /// Returns the loaded value or throws if not yet loaded. For lazy access, use <c>await</c> on the wrapping property.
    /// </summary>
    public T? ValueOrThrow => _state switch
    {
        State.Loaded => _value,
        State.LoadedNull => null,
        _ => throw new InvalidOperationException(
            $"EntityRef<{typeof(T).Name}> for IRI '{_iri}' is not loaded. Await the property or open an EntitySession."),
    };

    public static EntityRef<T> ForIri(string iri)
    {
        if (string.IsNullOrWhiteSpace(iri))
            throw new ArgumentException("IRI must not be empty.", nameof(iri));
        return new EntityRef<T>(iri, State.Unloaded, null);
    }

    public static EntityRef<T> Loaded(T value)
    {
        ArgumentNullException.ThrowIfNull(value);
        return new EntityRef<T>(value.Iri, State.Loaded, value);
    }

    public static EntityRef<T> LoadedNull(string iri)
    {
        if (string.IsNullOrWhiteSpace(iri))
            throw new ArgumentException("IRI must not be empty.", nameof(iri));
        return new EntityRef<T>(iri, State.LoadedNull, null);
    }

    /// <summary>
    /// Resolve the value via the ambient <see cref="EntitySession"/>. Caches the result inside this ref.
    /// </summary>
    public async ValueTask<T?> ResolveAsync(CancellationToken cancellationToken = default)
    {
        if (_state != State.Unloaded) return _value;
        var loader = EntitySession.RequireLoader();
        var loaded = await loader.LoadAsync<T>(_iri, cancellationToken).ConfigureAwait(false);
        if (loaded is null)
        {
            _state = State.LoadedNull;
            _value = null;
        }
        else
        {
            _state = State.Loaded;
            _value = loaded;
        }
        return loaded;
    }

    /// <summary>Awaiter support so callers can write <c>await someRef</c>.</summary>
    public ValueTaskAwaiter<T?> GetAwaiter() => ResolveAsync().GetAwaiter();
}
