using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Forge.Capability.Generators;

/// <summary>
/// Emits a single <c>.g.caps.cs</c> source file containing command records,
/// response records, and <c>ICapabilityHandler</c> implementations for every
/// requested <see cref="CrudMethod"/> on an entity.
/// </summary>
internal static class CrudCapabilityEmitter
{
    private const string Cap  = "global::Forge.Capability";
    private const string List = "global::System.Collections.Generic.List";
    private const string RoList = "global::System.Collections.Generic.IReadOnlyList";
    private const string Vt   = "global::System.Threading.Tasks.ValueTask";
    private const string Ct   = "global::System.Threading.CancellationToken";

    public static string Emit(CrudCapabilityEntityModel m)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();

        var hasNs = m.Namespace.Length > 0;
        if (hasNs) sb.Append("namespace ").Append(m.Namespace).AppendLine(";").AppendLine();

        // ── Read{T}Response / list-item record ────────────────────────────────
        if (m.NeedsReadResponse)
        {
            EmitReadResponse(sb, m);
            sb.AppendLine();
        }

        // ── Create ────────────────────────────────────────────────────────────
        if (m.HasCreate)
        {
            EmitCreateTypes(sb, m);
            sb.AppendLine();
        }

        // ── Read ──────────────────────────────────────────────────────────────
        if (m.HasRead)
        {
            EmitReadHandler(sb, m);
            sb.AppendLine();
        }

        // ── Update ────────────────────────────────────────────────────────────
        if (m.HasUpdate)
        {
            EmitUpdateTypes(sb, m);
            sb.AppendLine();
        }

        // ── Delete ────────────────────────────────────────────────────────────
        if (m.HasDelete)
        {
            EmitDeleteTypes(sb, m);
            sb.AppendLine();
        }

        // ── List ──────────────────────────────────────────────────────────────
        if (m.HasList)
        {
            EmitListTypes(sb, m);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Read response (shared with List)
    // ─────────────────────────────────────────────────────────────────────────

    private static void EmitReadResponse(StringBuilder sb, CrudCapabilityEntityModel m)
    {
        sb.Append("public sealed record Read").Append(m.TypeName).Append("Response(string Iri");
        AppendRecordParams(sb, m.ReadResponseProps);
        sb.AppendLine(");");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Create
    // ─────────────────────────────────────────────────────────────────────────

    private static void EmitCreateTypes(StringBuilder sb, CrudCapabilityEntityModel m)
    {
        // Command
        sb.Append("public sealed record Create").Append(m.TypeName).Append("Command(");
        AppendRecordParamsInner(sb, m.CreateCommandProps);
        sb.AppendLine(");");

        // Response
        sb.Append("public sealed record Create").Append(m.TypeName).AppendLine("Response(string Iri);");
        sb.AppendLine();

        // Handler
        var cmdType = $"Create{m.TypeName}Command";
        var resType = $"Create{m.TypeName}Response";
        EmitHandlerHeader(sb, m, "create", cmdType, resType);
        sb.AppendLine("    {");

        // Body: build object initializer
        if (m.CreateCommandProps.Length > 0)
        {
            sb.Append("        var entity = new ").Append(m.FullyQualifiedName).AppendLine();
            sb.AppendLine("        {");
            foreach (var p in m.CreateCommandProps)
                sb.Append("            ").Append(p.Name).Append(" = command.").Append(p.Name).AppendLine(",");
            sb.AppendLine("        };");
        }
        else
        {
            sb.Append("        var entity = new ").Append(m.FullyQualifiedName).AppendLine("();");
        }

        sb.AppendLine("        await entity.CreateAsync(cancellationToken);");
        sb.Append("        return new ").Append(Cap).Append(".CapabilityResult<").Append(resType).AppendLine(">.Ok(");
        sb.Append("            new ").Append(resType).AppendLine("(entity.Iri));");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Read
    // ─────────────────────────────────────────────────────────────────────────

    private static void EmitReadHandler(StringBuilder sb, CrudCapabilityEntityModel m)
    {
        var cmdType = $"Read{m.TypeName}Command";
        var resType = $"Read{m.TypeName}Response";

        sb.Append("public sealed record ").Append(cmdType).AppendLine("(string Iri);");
        sb.AppendLine();

        EmitHandlerHeader(sb, m, "read", cmdType, resType);
        sb.AppendLine("    {");

        // Load entity
        sb.Append("        var entity = await ").Append(m.FullyQualifiedName)
          .AppendLine(".ReadAsync(command.Iri, cancellationToken);");

        // Not-found guard
        EmitNotFoundGuard(sb, m.TypeName, resType);

        // Map to response
        sb.Append("        return new ").Append(Cap).Append(".CapabilityResult<").Append(resType).AppendLine(">.Ok(");
        sb.Append("            new ").Append(resType).Append("(entity.Iri");
        foreach (var p in m.ReadResponseProps)
            sb.Append(", entity.").Append(p.Name);
        sb.AppendLine("));");

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Update
    // ─────────────────────────────────────────────────────────────────────────

    private static void EmitUpdateTypes(StringBuilder sb, CrudCapabilityEntityModel m)
    {
        var updateProps = m.UpdateCommandProps;

        // Command: Iri + settable data props
        sb.Append("public sealed record Update").Append(m.TypeName).Append("Command(string Iri");
        AppendRecordParams(sb, updateProps);
        sb.AppendLine(");");

        // Response
        sb.Append("public sealed record Update").Append(m.TypeName).AppendLine("Response(string Iri);");
        sb.AppendLine();

        // Handler
        var cmdType = $"Update{m.TypeName}Command";
        var resType = $"Update{m.TypeName}Response";
        EmitHandlerHeader(sb, m, "update", cmdType, resType);
        sb.AppendLine("    {");

        // Load entity
        sb.Append("        var entity = await ").Append(m.FullyQualifiedName)
          .AppendLine(".ReadAsync(command.Iri, cancellationToken);");

        EmitNotFoundGuard(sb, m.TypeName, resType);

        // Assign settable props
        foreach (var p in updateProps)
            sb.Append("        entity.").Append(p.Name).Append(" = command.").Append(p.Name).AppendLine(";");

        sb.AppendLine("        await entity.UpdateAsync(cancellationToken);");
        sb.Append("        return new ").Append(Cap).Append(".CapabilityResult<").Append(resType).AppendLine(">.Ok(");
        sb.Append("            new ").Append(resType).AppendLine("(entity.Iri));");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Delete
    // ─────────────────────────────────────────────────────────────────────────

    private static void EmitDeleteTypes(StringBuilder sb, CrudCapabilityEntityModel m)
    {
        var cmdType = $"Delete{m.TypeName}Command";
        var resType = $"Delete{m.TypeName}Response";

        sb.Append("public sealed record ").Append(cmdType).AppendLine("(string Iri);");
        sb.Append("public sealed record ").Append(resType).AppendLine("();");
        sb.AppendLine();

        EmitHandlerHeader(sb, m, "delete", cmdType, resType);
        sb.AppendLine("    {");

        sb.Append("        var entity = await ").Append(m.FullyQualifiedName)
          .AppendLine(".ReadAsync(command.Iri, cancellationToken);");

        EmitNotFoundGuard(sb, m.TypeName, resType);

        sb.AppendLine("        await entity.DeleteAsync(cancellationToken);");
        sb.Append("        return new ").Append(Cap).Append(".CapabilityResult<").Append(resType).AppendLine(">.Ok(");
        sb.Append("            new ").Append(resType).AppendLine("());");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // List
    // ─────────────────────────────────────────────────────────────────────────

    private static void EmitListTypes(StringBuilder sb, CrudCapabilityEntityModel m)
    {
        var itemType = $"Read{m.TypeName}Response";
        var cmdType  = $"List{m.TypeName}Command";
        var resType  = $"List{m.TypeName}Response";

        sb.Append("public sealed record ").Append(cmdType).AppendLine("();");
        sb.Append("public sealed record ").Append(resType).Append("(")
          .Append(RoList).Append("<").Append(itemType).AppendLine("> Items);");
        sb.AppendLine();

        EmitHandlerHeader(sb, m, "list", cmdType, resType);
        sb.AppendLine("    {");

        sb.Append("        var items = new ").Append(List).Append("<").Append(itemType).AppendLine(">();");
        sb.Append("        await foreach (var entity in ").Append(m.FullyQualifiedName)
          .AppendLine(".ListAsync(cancellationToken))");
        sb.AppendLine("        {");
        sb.Append("            items.Add(new ").Append(itemType).Append("(entity.Iri");
        foreach (var p in m.ReadResponseProps)
            sb.Append(", entity.").Append(p.Name);
        sb.AppendLine("));");
        sb.AppendLine("        }");

        sb.Append("        return new ").Append(Cap).Append(".CapabilityResult<").Append(resType).AppendLine(">.Ok(");
        sb.Append("            new ").Append(resType).AppendLine("(items));");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Shared helpers
    // ─────────────────────────────────────────────────────────────────────────

    private static void EmitHandlerHeader(
        StringBuilder sb,
        CrudCapabilityEntityModel m,
        string operation,
        string cmdType,
        string resType)
    {
        var handlerName = operation[0].ToString().ToUpperInvariant() + operation.Substring(1)
                          + m.TypeName + "Handler";

        sb.Append("[").Append(Cap).Append(".CapabilityAttribute(\"")
          .Append(m.CapabilityPathSegment).Append(".").Append(operation).AppendLine("\")]");
        sb.Append("public sealed class ").Append(handlerName)
          .Append(" : ").Append(Cap).Append(".ICapabilityHandler<").Append(cmdType).Append(", ").Append(resType).AppendLine(">")
          .AppendLine("{");

        // HandleAsync signature
        sb.Append("    public async ").Append(Vt)
          .Append("<").Append(Cap).Append(".CapabilityResult<").Append(resType).AppendLine(">> HandleAsync(");
        sb.Append("        ").Append(cmdType).AppendLine(" command,");
        sb.Append("        ").Append(Cap).AppendLine(".CapabilityContext context,");
        sb.Append("        ").Append(Ct).AppendLine(" cancellationToken = default)");
    }

    private static void EmitNotFoundGuard(StringBuilder sb, string typeName, string resType)
    {
        sb.AppendLine("        if (entity is null)");
        sb.Append("            return new ").Append(Cap).Append(".CapabilityResult<").Append(resType).AppendLine(">.Fail(");
        sb.Append("                new ").Append(Cap).Append(".CapabilityError(\"NOT_FOUND\", $\"")
          .Append(typeName).AppendLine(" '{command.Iri}' not found.\"));");
    }

    /// <summary>Appends positional record params after an already-open paren, then closes it.</summary>
    private static void AppendRecordParams(StringBuilder sb, ImmutableArray<PropModel> props)
    {
        foreach (var p in props)
            sb.Append(", ").Append(p.TypeDisplay).Append(" ").Append(p.Name);
    }

    /// <summary>Appends positional record params inside an already-open paren (no leading comma).</summary>
    private static void AppendRecordParamsInner(StringBuilder sb, ImmutableArray<PropModel> props)
    {
        for (int i = 0; i < props.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(props[i].TypeDisplay).Append(" ").Append(props[i].Name);
        }
    }
}
