using System.Linq;
using System.Text;

namespace Forge.Entity.Generators;

internal static class EntityEmitter
{
    public static string Emit(EntityModel m, EntityRegistry registry)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Forge.Entity;");
        sb.AppendLine();

        var hasNamespace = m.Namespace.Length > 0;
        if (hasNamespace) sb.Append("namespace ").Append(m.Namespace).AppendLine(";").AppendLine();

        // Child entities inherit from their parent entity class; root entities inherit EntityBase.
        var baseClass = m.BaseEntityTypeFqn ?? "global::Forge.Entity.EntityBase";

        sb.Append(m.IsSealed ? "sealed " : "")
          .Append("partial class ")
          .Append(m.TypeName)
          .Append(" : ").AppendLine(baseClass)
          .AppendLine("{");

        if (!m.IsEntitySubtype)
        {
            EmitIdentityFields(sb, m);
            EmitIdentityPartProperties(sb, m);
        }
        else if (m.IdentityStrategy == IdentityStrategy.UuidV4)
        {
            // UuidV4 subtypes need an explicit ctor pair — emitting (Guid) suppresses the
            // C# auto-generated default ctor so we also emit the parameterless one.
            EmitSubtypeV4Ctors(sb, m);
        }

        EmitOwningSingleRefs(sb, m, registry);
        EmitOwningCollections(sb, m, registry);
        EmitInverseRefs(sb, m);
        EmitInverseCollections(sb, m);

        if (!m.IsEntitySubtype)
        {
            if (m.IdentityStrategy == IdentityStrategy.Path
                || m.IdentityStrategy == IdentityStrategy.UuidV5)
            {
                EmitIdentityMaterialization(sb, m);
                sb.AppendLine("    protected override void EnsureIdentity() => MaterializeIdentity();");
                sb.AppendLine();
            }

            if (m.IdentityStrategy == IdentityStrategy.UuidV5)
                EmitUuidV5Helper(sb);

            if (m.IsEnumeration)
                EmitEnumerationStaticInit(sb, m);
        }

        if (m.IsObjectBearing)
            EmitObjectBearingMembers(sb, m);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ------------------------------------------------------- ObjectBearing

    private static void EmitObjectBearingMembers(StringBuilder sb, EntityModel m)
    {
        sb.AppendLine("    [Predicate(\"objectKey\")]");
        sb.AppendLine("    public string? ObjectKey { get; set; }");
        sb.AppendLine();
        sb.AppendLine("    [Predicate(\"contentType\")]");
        sb.AppendLine("    public string? ContentType { get; set; }");
        sb.AppendLine();
        sb.Append("    public const string ForgeObjectStoreKey = \"").Append(m.ObjectStoreKey).AppendLine("\";");
        sb.AppendLine();
    }

    // ---------------------------------------------------------------- Identity

    /// <summary>
    /// For UuidV4 entity subtypes: emitting the explicit (Guid) ctor suppresses the C# default
    /// ctor, so we also emit a public parameterless ctor that forwards to the parent's new-instance
    /// ctor (which seals the IRI with a fresh UUID).
    /// </summary>
    private static void EmitSubtypeV4Ctors(StringBuilder sb, EntityModel m)
    {
        sb.Append("    public ").Append(m.TypeName).AppendLine("() : base() { }");
        sb.AppendLine();
        sb.Append("    internal ").Append(m.TypeName)
          .AppendLine("(global::System.Guid persistedUuid) : base(persistedUuid) { }");
        sb.AppendLine();
    }

    private static void EmitIdentityFields(StringBuilder sb, EntityModel m)
    {
        switch (m.IdentityStrategy)
        {
            case IdentityStrategy.UuidV4:
                sb.AppendLine("    private readonly global::System.Guid __forge_identityUuid;");
                sb.AppendLine();
                sb.Append("    public ").Append(m.TypeName).AppendLine("()").AppendLine("    {");
                sb.AppendLine("        __forge_identityUuid = global::System.Guid.NewGuid();");
                sb.AppendLine("        Iri = global::Forge.Entity.EntityOptions.Current.BaseIri + " +
                              FormatPathSegment(m) + " + \"/\" + __forge_identityUuid.ToString(\"D\");");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.Append("    internal ").Append(m.TypeName).AppendLine("(global::System.Guid persistedUuid)");
                sb.AppendLine("    {");
                sb.AppendLine("        __forge_identityUuid = persistedUuid;");
                sb.AppendLine("        HydrateIri(global::Forge.Entity.EntityOptions.Current.BaseIri + " +
                              FormatPathSegment(m) + " + \"/\" + persistedUuid.ToString(\"D\"));");
                sb.AppendLine("    }");
                sb.AppendLine();
                break;

            case IdentityStrategy.UuidV5:
                sb.AppendLine("    private global::System.Guid __forge_identityUuid;");
                sb.AppendLine();
                sb.Append("    public ").Append(m.TypeName).AppendLine("() { }");
                sb.AppendLine();
                sb.Append("    internal ").Append(m.TypeName).AppendLine("(global::System.Guid persistedUuid)");
                sb.AppendLine("    {");
                sb.AppendLine("        __forge_identityUuid = persistedUuid;");
                sb.AppendLine("        HydrateIri(global::Forge.Entity.EntityOptions.Current.BaseIri + " +
                              FormatPathSegment(m) + " + \"/\" + persistedUuid.ToString(\"D\"));");
                sb.AppendLine("    }");
                sb.AppendLine();
                break;

            case IdentityStrategy.Path:
                // No backing fields needed; identity is derived from named identity-part fields below.
                break;
        }
    }

    private static void EmitIdentityPartProperties(StringBuilder sb, EntityModel m)
    {
        foreach (var part in m.IdentityParts)
        {
            sb.Append("    private ").Append(part.TypeDisplayName).Append(" __forge_part_")
              .Append(part.PropertyName).Append(part.IsString ? " = \"\";" : ";").AppendLine();
            sb.Append("    public partial ").Append(part.TypeDisplayName).Append(' ').AppendLine(part.PropertyName);
            sb.AppendLine("    {");
            sb.Append("        get => __forge_part_").Append(part.PropertyName).AppendLine(";");
            sb.AppendLine("        init");
            sb.AppendLine("        {");
            sb.AppendLine("            GuardIdentityMutation();");
            sb.Append("            __forge_part_").Append(part.PropertyName).AppendLine(" = value;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    private static void EmitIdentityMaterialization(StringBuilder sb, EntityModel m)
    {
        sb.AppendLine("    /// <summary>Compose and seal the IRI from the current identity-part values.</summary>");
        sb.AppendLine("    public void MaterializeIdentity()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (IsIdentitySealed) return;");

        if (m.IdentityStrategy == IdentityStrategy.Path)
        {
            sb.Append("        var __iri = global::Forge.Entity.EntityOptions.Current.BaseIri")
              .Append(" + ").Append(FormatPathSegment(m));
            foreach (var part in m.IdentityParts)
            {
                sb.Append(" + \"/\" + global::System.Convert.ToString(__forge_part_")
                  .Append(part.PropertyName)
                  .Append(", global::System.Globalization.CultureInfo.InvariantCulture)");
            }
            sb.AppendLine(";");
            sb.AppendLine("        Iri = __iri;");
        }
        else // UuidV5
        {
            // Build the canonical name string (deterministic input) from identity parts.
            sb.Append("        var __name = \"\"");
            foreach (var part in m.IdentityParts)
            {
                sb.Append(" + \"/\" + global::System.Convert.ToString(__forge_part_")
                  .Append(part.PropertyName)
                  .Append(", global::System.Globalization.CultureInfo.InvariantCulture)");
            }
            sb.AppendLine(";");

            // Namespace GUID: explicit override or auto-derived from BaseIri + Path at runtime.
            if (!string.IsNullOrWhiteSpace(m.IdentityNamespace)
                && System.Guid.TryParse(m.IdentityNamespace, out var explicitNs))
            {
                sb.Append("        var __nsGuid = new global::System.Guid(\"")
                  .Append(explicitNs.ToString("D")).AppendLine("\");");
            }
            else
            {
                // Derive: UuidV5(RFC4122-URL-namespace, BaseIri + "/" + Path)
                // RFC 4122 URL namespace: 6ba7b810-9dad-11d1-80b4-00c04fd430c8
                sb.Append("        var __nsGuid = __Forge_ComputeUuidV5(")
                  .Append("new global::System.Guid(\"6ba7b810-9dad-11d1-80b4-00c04fd430c8\"), ")
                  .Append("global::Forge.Entity.EntityOptions.Current.BaseIri + ")
                  .Append(FormatPathSegment(m))
                  .AppendLine(");");
            }

            sb.Append("        __forge_identityUuid = __Forge_ComputeUuidV5(__nsGuid, __name);").AppendLine();
            sb.Append("        Iri = global::Forge.Entity.EntityOptions.Current.BaseIri + ")
              .Append(FormatPathSegment(m))
              .AppendLine(" + \"/\" + __forge_identityUuid.ToString(\"D\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitUuidV5Helper(StringBuilder sb)
    {
        sb.AppendLine("    private static global::System.Guid __Forge_ComputeUuidV5(global::System.Guid namespaceId, string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        var __nsBytes = namespaceId.ToByteArray();");
        sb.AppendLine("        global::System.Array.Reverse(__nsBytes, 0, 4);");
        sb.AppendLine("        global::System.Array.Reverse(__nsBytes, 4, 2);");
        sb.AppendLine("        global::System.Array.Reverse(__nsBytes, 6, 2);");
        sb.AppendLine("        var __nameBytes = global::System.Text.Encoding.UTF8.GetBytes(name);");
        sb.AppendLine("        var __combined = new byte[__nsBytes.Length + __nameBytes.Length];");
        sb.AppendLine("        global::System.Buffer.BlockCopy(__nsBytes, 0, __combined, 0, __nsBytes.Length);");
        sb.AppendLine("        global::System.Buffer.BlockCopy(__nameBytes, 0, __combined, __nsBytes.Length, __nameBytes.Length);");
        sb.AppendLine("        byte[] __hash;");
        sb.AppendLine("        using (var __sha1 = global::System.Security.Cryptography.SHA1.Create())");
        sb.AppendLine("            __hash = __sha1.ComputeHash(__combined);");
        sb.AppendLine("        var __out = new byte[16];");
        sb.AppendLine("        global::System.Array.Copy(__hash, __out, 16);");
        sb.AppendLine("        __out[6] = (byte)((__out[6] & 0x0F) | (5 << 4));");
        sb.AppendLine("        __out[8] = (byte)((__out[8] & 0x3F) | 0x80);");
        sb.AppendLine("        global::System.Array.Reverse(__out, 0, 4);");
        sb.AppendLine("        global::System.Array.Reverse(__out, 4, 2);");
        sb.AppendLine("        global::System.Array.Reverse(__out, 6, 2);");
        sb.AppendLine("        return new global::System.Guid(__out);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string FormatPathSegment(EntityModel m) =>
        string.IsNullOrEmpty(m.Path) ? "\"\"" : $"\"/{m.Path}\"";

    private static void EmitEnumerationStaticInit(StringBuilder sb, EntityModel m)
    {
        // Generated static ctor seals every public static readonly field of the type
        // by calling MaterializeIdentity() on each (Path strategy).
        sb.Append("    static ").Append(m.TypeName).AppendLine("()");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var __field in typeof(" + m.TypeName +
                      ").GetFields(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static))");
        sb.AppendLine("        {");
        sb.AppendLine("            if (__field.FieldType != typeof(" + m.TypeName + ")) continue;");
        sb.AppendLine("            var __instance = (" + m.TypeName + "?)__field.GetValue(null);");
        sb.AppendLine("            __instance?.MaterializeIdentity();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // ---------------------------------------------------------------- Owning single

    private static void EmitOwningSingleRefs(StringBuilder sb, EntityModel m, EntityRegistry registry)
    {
        foreach (var r in m.References)
        {
            if (r.Kind != RefKind.OwningSingle) continue;

            var fieldName = "__forge_ref_" + r.PropertyName;
            var refType = "global::Forge.Entity.EntityRef<" + r.TargetTypeDisplayName + ">?";
            sb.Append("    private ").Append(refType).Append(' ').Append(fieldName).AppendLine(";");

            sb.Append("    public partial ").Append(refType).Append(' ').AppendLine(r.PropertyName);
            sb.AppendLine("    {");
            sb.Append("        get => ").Append(fieldName).AppendLine(";");
            sb.AppendLine("        set");
            sb.AppendLine("        {");

            var inverseProp = registry.FindInverseSetter(r.TargetTypeFullName, r.PropertyName);
            if (inverseProp is not null)
            {
                var ownerRefType = "global::Forge.Entity.EntityRef<" + m.TypeName + ">.Loaded(this)";
                sb.Append("            if (").Append(fieldName).AppendLine("?.HasValue == true)");
                sb.Append("                ").Append(fieldName).Append("!.ValueOrThrow!.__Forge_Set_")
                  .Append(inverseProp).AppendLine("(null);");
                sb.Append("            ").Append(fieldName).AppendLine(" = value;");
                sb.AppendLine("            if (value?.HasValue == true)");
                sb.Append("                value!.ValueOrThrow!.__Forge_Set_").Append(inverseProp)
                  .Append('(').Append(ownerRefType).AppendLine(");");
            }
            else
            {
                sb.Append("            ").Append(fieldName).AppendLine(" = value;");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    // ---------------------------------------------------------------- Owning collections

    private static void EmitOwningCollections(StringBuilder sb, EntityModel m, EntityRegistry registry)
    {
        foreach (var r in m.References)
        {
            if (r.Kind != RefKind.OwningCollection) continue;

            var fieldName = "__forge_coll_" + r.PropertyName;
            var targetDisplay = r.TargetTypeDisplayName;
            sb.Append("    private global::Forge.Entity.EntityRefCollection<").Append(targetDisplay)
              .Append(">? ").Append(fieldName).AppendLine(";");

            sb.Append("    public partial global::Forge.Entity.EntityRefCollection<").Append(targetDisplay)
              .Append("> ").Append(r.PropertyName).Append(" => ").Append(fieldName)
              .AppendLine(" ??= __Forge_Build_" + r.PropertyName + "();");
            sb.AppendLine();

            sb.Append("    private global::Forge.Entity.EntityRefCollection<").Append(targetDisplay)
              .Append("> __Forge_Build_").Append(r.PropertyName).AppendLine("()");
            sb.AppendLine("    {");
            var inverse = registry.FindInverse(r.TargetTypeFullName, r.PropertyName);
            if (inverse is { IsCollection: false } single)
            {
                // Inverse is a single ref: set/clear via __Forge_Set_X
                AppendCollectionCtorOpen(sb, r, targetDisplay);
                sb.AppendLine("            onAdd: __child =>");
                sb.AppendLine("            {");
                sb.Append("                __child.__Forge_Set_").Append(single.PropertyName)
                  .Append("(global::Forge.Entity.EntityRef<").Append(m.TypeName).AppendLine(">.Loaded(this));");
                sb.AppendLine("                return default;");
                sb.AppendLine("            },");
                sb.AppendLine("            onRemove: __child =>");
                sb.AppendLine("            {");
                sb.Append("                __child.__Forge_Set_").Append(single.PropertyName).AppendLine("(null);");
                sb.AppendLine("                return default;");
                sb.AppendLine("            });");
            }
            else if (inverse is { IsCollection: true } coll)
            {
                // Inverse is a collection: use __Forge_AddTo_X / __Forge_RemoveFrom_X
                AppendCollectionCtorOpen(sb, r, targetDisplay);
                sb.AppendLine("            onAdd: async __child =>");
                sb.AppendLine("            {");
                sb.Append("                await __child.__Forge_AddTo_").Append(coll.PropertyName).AppendLine("(this);");
                sb.AppendLine("            },");
                sb.AppendLine("            onRemove: async __child =>");
                sb.AppendLine("            {");
                sb.Append("                await __child.__Forge_RemoveFrom_").Append(coll.PropertyName).AppendLine("(this);");
                sb.AppendLine("            });");
            }
            else
            {
                AppendCollectionCtorNoHooks(sb, r, targetDisplay);
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    // ---------------------------------------------------------------- Inverse refs (single)

    private static void EmitInverseRefs(StringBuilder sb, EntityModel m)
    {
        foreach (var r in m.References)
        {
            if (r.Kind != RefKind.InverseSingle) continue;

            var fieldName = "__forge_inv_" + r.PropertyName;
            sb.Append("    private global::Forge.Entity.EntityRef<").Append(r.TargetTypeDisplayName)
              .Append(">? ").Append(fieldName).AppendLine(";");

            sb.Append("    public partial global::Forge.Entity.EntityRef<")
              .Append(r.TargetTypeDisplayName).Append(">? ").Append(r.PropertyName)
              .Append(" => ").Append(fieldName).AppendLine(";");

            sb.Append("    internal void __Forge_Set_").Append(r.PropertyName)
              .Append("(global::Forge.Entity.EntityRef<").Append(r.TargetTypeDisplayName)
              .AppendLine(">? value)");
            sb.Append("    { ").Append(fieldName).AppendLine(" = value; }");
            sb.AppendLine();
        }
    }

    // ---------------------------------------------------------------- Inverse collections (m:n)

    private static void EmitInverseCollections(StringBuilder sb, EntityModel m)
    {
        foreach (var r in m.References)
        {
            if (r.Kind != RefKind.InverseCollection) continue;

            var fieldName = "__forge_invcoll_" + r.PropertyName;
            var targetDisplay = r.TargetTypeDisplayName;

            sb.Append("    private global::Forge.Entity.EntityRefCollection<").Append(targetDisplay)
              .Append(">? ").Append(fieldName).AppendLine(";");

            sb.Append("    public partial global::Forge.Entity.EntityRefCollection<").Append(targetDisplay)
              .Append("> ").Append(r.PropertyName).Append(" => ").Append(fieldName);
            if (r.IsLazy)
            {
                sb.Append(" ??= new global::Forge.Entity.LazyInverseEntityRefCollectionImpl<").Append(targetDisplay).AppendLine(">(); // deferred — IsResolved=false, omitted from HTTP responses");
            }
            else
            {
                sb.Append(" ??= new global::Forge.Entity.EntityRefCollectionImpl<").Append(targetDisplay).AppendLine(">(); // internal — populated by owning side");
            }
            sb.AppendLine();

            // __Forge_AddTo_X — called by the owning side's onAdd hook
            sb.Append("    internal global::System.Threading.Tasks.ValueTask __Forge_AddTo_").Append(r.PropertyName)
              .Append("(").Append(targetDisplay).AppendLine(" item)");
            sb.AppendLine("    {");
            if (r.IsLazy)
            {
                sb.Append("        ").Append(fieldName).Append(" ??= new global::Forge.Entity.LazyInverseEntityRefCollectionImpl<").Append(targetDisplay).AppendLine(">();");
            }
            else
            {
                sb.Append("        ").Append(fieldName).Append(" ??= new global::Forge.Entity.EntityRefCollectionImpl<").Append(targetDisplay).AppendLine(">();");
            }
            sb.Append("        return ").Append(fieldName).AppendLine(".AddAsync(item);");
            sb.AppendLine("    }");
            sb.AppendLine();

            // __Forge_RemoveFrom_X — called by the owning side's onRemove hook
            sb.Append("    internal global::System.Threading.Tasks.ValueTask __Forge_RemoveFrom_").Append(r.PropertyName)
              .Append("(").Append(targetDisplay).AppendLine(" item)");
            sb.AppendLine("    {");
            sb.Append("        if (").Append(fieldName).AppendLine(" is null) return default;");
            sb.Append("        return ").Append(fieldName).AppendLine(".RemoveAsync(item);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    // ---------------------------------------------------------------- Collection ctor helpers

    private static void AppendCollectionCtorOpen(StringBuilder sb, RefModel r, string targetDisplay)
    {
        if (r.IsLazy)
        {
            sb.Append("        return new global::Forge.Entity.DeferredEntityRefCollectionImpl<")
              .Append(targetDisplay).AppendLine(">(");
            sb.AppendLine("            ownerIriSelector: () => Iri,");
            sb.Append("            predicate: \"").Append(r.Predicate).AppendLine("\",");
        }
        else
        {
            sb.Append("        return new global::Forge.Entity.EntityRefCollectionImpl<")
              .Append(targetDisplay).AppendLine(">(");
        }
    }

    private static void AppendCollectionCtorNoHooks(StringBuilder sb, RefModel r, string targetDisplay)
    {
        if (r.IsLazy)
        {
            sb.Append("        return new global::Forge.Entity.DeferredEntityRefCollectionImpl<")
              .Append(targetDisplay).Append(">(ownerIriSelector: () => Iri, predicate: \"")
              .Append(r.Predicate).AppendLine("\");");
        }
        else
        {
            sb.Append("        return new global::Forge.Entity.EntityRefCollectionImpl<")
              .Append(targetDisplay).AppendLine(">(); ");
        }
    }
}
